version: '3.8'

services:
  # O Backend (Node.js) que recebe os Webhooks para salvar mensagens
  app_backend:
    build: 
      context: ./server
    container_name: ublochat_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=967d7e6b537be56e6677b96a606c7d8b
      - DB_NAME=postgres
    networks:
      - ublochatnet


  # Frontend
  app_frontend:
    build:
      context: .
      args:
        - VITE_SUPABASE_URL=https://rormftnssmqwcluvlszg.supabase.co
        - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvcm1mdG5zc21xd2NsdXZsc3zgIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NDMwNzYsImV4cCI6MjA4NDUxOTA3Nn0.Jb8d8JwEdCyubUVbMTNXi5y9VKYmVaOeQi85RwplB-E
        - VITE_EVOLUTION_API_URL=https://api.ublochat.com.br
        - VITE_EVOLUTION_API_KEY=f534ab200345bc2b35ef679dde6e61ec
    container_name: ublochat_frontend
    restart: always
    expose:
      - "80"
    networks:
      - ublochatnet

  # Caddy
  caddy:
    image: caddy:latest
    container_name: ublochat_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ublochatnet
    depends_on:
      - app_frontend
      - app_backend

volumes:
  caddy_data:
  caddy_config:
  postgres_data:  # Volume persistente do banco

networks:
  ublochatnet:
    external: true

