version: '3.8'

services:
  # O Backend (Node.js) que recebe os Webhooks para salvar mensagens
  app_backend:
    build: 
      context: ./server
    container_name: ublochat_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_TYPE=postgres
      # Conex√£o Interna com o banco Postgres abaixo
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=supabase_admin
      - DB_PASS=967d7e6b537be56e6677b96a606c7d8b
      - DB_NAME=postgres
    networks:
      - ublochatnet
    depends_on:
      - postgres_db

  # Banco de Dados (Postgres)
  postgres_db:
    image: postgres:15-alpine
    container_name: ublochat_db
    restart: always
    environment:
      POSTGRES_USER: supabase_admin
      POSTGRES_PASSWORD: 967d7e6b537be56e6677b96a606c7d8b
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ublochatnet

  # Frontend
  app_frontend:
    build:
      context: .
      args:
        - VITE_SUPABASE_URL=http://localhost:54321
        - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzE1MDUwODAwLAogICJleHAiOiAxODcyODE3MjAwCn0.-Ju74JE1Hpyg5-f8Naz5qkgGNLOAx5PwEx96R3B8yW8
        - VITE_EVOLUTION_API_URL=https://api.ublochat.com.br
        - VITE_EVOLUTION_API_KEY=f534ab200345bc2b35ef679dde6e61ec
    container_name: ublochat_frontend
    restart: always
    expose:
      - "80"
    networks:
      - ublochatnet

  # Caddy
  caddy:
    image: caddy:latest
    container_name: ublochat_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ublochatnet
    depends_on:
      - app_frontend
      - app_backend

volumes:
  caddy_data:
  caddy_config:
  postgres_data:  # Volume persistente do banco

networks:
  ublochatnet:
    external: true

